services:

  backend:
    build: ./mern-auth/backend
    ports:
      - "5001:5001"
    env_file:
      - ./mern-auth/backend/.env

  frontend:
    build: ./mern-auth/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  ml-service:
    build: ./stock-ml-service
    ports:
      - "8001:8001"