name: Stock Market CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:

    # 1️⃣ Checkout repository
    - name: Checkout code
      uses: actions/checkout@v4


    # 2️⃣ Setup Node
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18


    # 3️⃣ Install Backend Dependencies
    - name: Install Backend Dependencies
      run: |
        cd mern-auth/backend
        npm install


    # 4️⃣ Install Frontend Dependencies
    - name: Install Frontend Dependencies
      run: |
        cd mern-auth/frontend
        npm install


    # 5️⃣ Setup Python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"


    # 6️⃣ Install ML Dependencies
    - name: Install ML Dependencies
      run: |
        cd stock-ml-service
        pip install -r requirements.txt


    # 7️⃣ Create Backend .env File (IMPORTANT FIX)
    - name: Create backend environment file
      run: |
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> mern-auth/backend/.env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> mern-auth/backend/.env


    # 8️⃣ Build Docker Containers
    - name: Build Docker Containers
      run: docker compose build


    # 9️⃣ Run Docker Containers
    - name: Run Containers
      run: |
        docker compose up -d
        sleep 25
        docker compose ps


    # 🔟 Stop Containers
    - name: Stop Containers
      run: docker compose down